dist: focal
language: python
python:
- '3.8'
services:
- docker
env:
  global:
  - ROLE_NAME: ahadns
  - secure: ZHIujIERXaOAuvoFlIMfOwSyciL+75yAThSjd0SibHyC2Qhcm8SJHTfwoFDymcqdw6OqOpWrRGEtdBmZDgXypbM9WFizEfsVGlSoX40j0GMmcMURz2c842cFOrToeZdkwJw0RziEsvfv95/IrF7NPyI6vQBU/3x1szkjo9x1YeSb/284VrbLlTCES0/L/K/pwASOyF3yD+C+M1B+74hJ/YdNDiEA/t16Qq2SGCBOaiB8cvJIXubeoLRVFB/ut63tjwHkUj8M79KJPImdLTa1cYK+2e8Crh2xmAFq7IUR1d2CPyqsC+mTo6zI+3d3LkH9pywhfRmXcrwf0ZB+Cdi1LIAwt9m7qThuwPFKsY8ztDhTxhJo9cCx77GSN52yvBeoqeGmYMem8pbGq5w5xabgQF50w6/XDOKbqkypnhDec/0V9lGSWm1qIbcjGEIKDVve3xJ8BHca0YYo9DjabqMp8WkLDkKvz/RmcEdrGmlVcwE/LyYnz9kuOC5or2yEgB8jDd163x93kPmwVnmdN6Y9YUEPa983h1gCV/cA9G1uJ6mxgiFQl69HKaJDaYTmX/XP12Dlr9uiKy7eN4pNeSMTYpS//xsJmrn9raDHIHuKJ4Qthdjk0TSqr7ygAoM68j6ZLWri6zsCS9vfVn834ku72pHFnQT7g9iCmLDnsBPVt7Y=
  - secure: QLKVnxoL1j1N3FOu0FKjoMjkdcrPHl/pW15UZZ0BTFq+BXUoa9gDYzOJhHTkItnIYuNIRFALue19xkO1ax5vFAjRzA/j0cUGWgZ/Lr6TzdjJgLV6FDdljhx/MmSuuQV9u0Bt+nf0CjPPYvU2/TOn9goLgRRBMZYrQca+/Mc08U61kuxa1a78ylQqtr5zTKKCj9lo4VdLmanY0qAtB2q+BEE83AeIgBHXssW3+ciUBIHPLE9ATfSQGXTFL01G/mR5Opok5AsWa4gDzJ4gWNKKvuv8wD5z2X/Hzcn9q/wjViR3kYYtQQqFPyazbEa1jhmxCF3G1WtWzYYoiqy5+VxGW8C5nvYMocs6ldrjyxNSbW6jsG3g6QQ8/cFMgMAxHYVEepY/g7HJdovf/1gf3ZxJW4Kx9/ThJc7zClXuZ8k3Zs/c4UJgtV6s2IGuIpcVubyNUC6noKVtQ/hLMKvTZzH3Hqsx0Ci94JVhcIT9/QpQ0KBZFdhEkrC/jzZH4hYtCBIUFSrTfW7fzNGLRATt0hXYkP/QLOwkHAuUPSg16D2B3WA2TVtg30/Gkfr6z12Xglp373W3VDN8YcMHQQXO+e2ZkfiJ9sHpbWtdWR70kYdrq1IlW5toT7xU3pJTbqXSR6I6z39mvCsstbnPLBT4En4h0Hctbw0kHA5ndi89isJlTpc=
  jobs:
  - MOLECULE_DISTRO: ubuntu2004
  - MOLECULE_DISTRO: ubuntu1804
cache:
- pip
install:
- pip install --upgrade pip
- pip install molecule-docker yamllint ansible-lint
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- molecule test
notifications: 
