---
- name: check doh-server service exists
  shell: |
    set -o pipefail
    systemctl is-enabled doh-server
  args:
    executable: /bin/bash
  become: true
  changed_when: false
  register: doh_server_svc
  failed_when: doh_server_svc.rc >= 2

- name: Completely remove old DoH server version (if installed)
  block:
    - name: Try stop DoH server (error here is fine...)
      systemd:
        name: doh-server
        state: stopped
      ignore_errors: true
      changed_when: false

    - name: Uninstall old DoH server version
      shell: |
        set -o pipefail
        cd; . /etc/profile; cd /opt/m13253/; make uninstall; cd
      args:
        executable: /bin/bash
      become: true
      changed_when: false

    - name: Remove old DoH server config files at /etc/dns-over-https/
      file:
        path: /etc/dns-over-https/
        state: absent
      changed_when: false

    - name: Remove old DoH server version at /opt/m13253/
      file:
        path: /opt/m13253/
        state: absent
      changed_when: false

  when: doh_server_svc.stdout == 'enabled'

- name: Setup DoH server
  block:
    - name: Download m13253 DoH server version {{ doh_version }}
      get_url:
        url: https://github.com/m13253/dns-over-https/archive/v{{ doh_version }}.tar.gz
        dest: /tmp/v{{ doh_version }}.tar.gz
        mode: "0644"
        force: yes
      changed_when: false

    - name: Create /opt/m13253/ directory
      file:
        path: /opt/m13253/
        state: directory
        mode: "0755"
      changed_when: false

    - name: Unpack m13253 DoH server version {{ doh_version }}
      unarchive:
        src: /tmp/v{{ doh_version }}.tar.gz
        dest: /opt/m13253/
        remote_src: yes
      changed_when: false

    - name: Move unpacked files
      shell: |
        set -o pipefail
        mv /opt/m13253/dns-over-https-{{ doh_version }}/* /opt/m13253/
      args:
        executable: /bin/bash
      become: true
      changed_when: false

    - name: Install DoH server as a service
      shell: |
        set -o pipefail
        cd; . /etc/profile; cd /opt/m13253/; make install
      environment:
        PATH: '{{ golang_path }}/go/bin:{{ ansible_env.PATH }}'
      args:
        executable: /bin/bash
      become: true
      changed_when: false

    - name: Enable DoH server
      systemd:
        name: doh-server
        enabled: yes
      changed_when: false

    - name: Disable DoH client
      systemd:
        name: doh-client
        enabled: false
      changed_when: false

    - name: Copy DoH server config
      template:
        src: m13253-doh/doh-server.conf.j2
        dest: /etc/dns-over-https/doh-server.conf
        mode: "0644"
        force: yes
      changed_when: false

    - name: Restart DoH server
      systemd:
        state: restarted
        daemon_reload: yes
        name: doh-server
      changed_when: false
