---
- name: Update /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    create: yes
    mode: 0644
    block: |
      127.0.0.1 localhost
      127.0.1.1   {{ ansible_hostname }}.localdomain    {{ ansible_hostname }}

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

      {{ ansible_default_ipv4.address }} {{ server_fqdn }}  {{ doh_endpoint }}  {{ dot_endpoint }}
  when: not ansible_virtualization_type | regex_search("docker|container")

- name: list required packages
  debug:
    msg: "{{ pkg_requirements }}"

- name: install requirements
  action: >
    {{ ansible_pkg_mgr }} name={{ pkg_requirements }} state=present update_cache=yes
  register: pkg_install_requirements
  until: pkg_install_requirements is succeeded
  retries: 3

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nginx
    - unbound
