---
# tasks file for ansible-role-ahadns

- name: get server specs
  debug:
    msg: "Identified machine with {{ num_cores }} cpu cores and {{ total_ram_mb }}mb RAM"

- name: Wait for systemd to complete initialization. # noqa 303
  command: systemctl is-system-running
  register: systemctl_status
  until: >
    'running' in systemctl_status.stdout or
    'degraded' in systemctl_status.stdout
  retries: 30
  delay: 5
  when: (ansible_service_mgr == 'systemd' and ansible_distribution == 'Fedora')
  changed_when: false

- name: Populate service facts
  shell: |
    set -o pipefail
    systemctl list-unit-files --no-pager --type service --all | grep -E 'systemd-resolved|^UNIT'
  args:
    executable: /bin/bash
  check_mode: no
  changed_when: false
  register: systemd_resolved_status

- name: disable systemd-resolved
  include: systemd-resolved.yml
  when: ('enabled' in systemd_resolved_status.stdout)

- name: start package install
  include: install.yml

- name: start server config
  include: configure.yml

- name: start ssl config
  include: ssl-certs.yml

- name: start nginx config
  include: nginx.yml

- name: start golang install
  include: golang.yml

- name: start doh-server install
  include: doh-server.yml

- name: start dns stats install
  include: server-stats.yml

- name: deploy resolv.conf template
  template:
    src: resolvconf/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: not ansible_virtualization_type | regex_search("docker|container")
