---
- name: Converge
  hosts: all
  vars:
    dhparam_key_size: 2048
    dhparam_remote_get: true
  tasks:

    - name: "Include ansible-role-ahadns"
      include_role:
        name: "ansible-role-ahadns"
