---
- name: Converge
  hosts: all
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: "Include ansible-role-ahadns"
      include_role:
        name: "ansible-role-ahadns"
